### ISSUE TITLE
Locale pt-br

### ISSUE THREAD

**Issue by meirinaldojunior** [electerm/electerm-locales#3]
I would like to contribute with the translation of the Brazilian Portuguese language, if you prefer, enable the repo's permission to write.

**Comment by zxdong262** [comment]
@meirinaldojunior thanks! you can just fork this repo, edit and submit a pull request to this repo, then I can merge it, no permission needed.
just click the `New pull request` from your fork.

**Comment by meirinaldojunior** [comment]
You're right! I did not remember this detail.
